#!/usr/bin/env bash
# git-secrets によるコミットメッセージテンプレート処理（インストール済みの場合のみ実行）
GIT_SECRETS=$(which git-secrets 2>/dev/null || true)
if [ -n "$GIT_SECRETS" ]; then
  "$GIT_SECRETS" --prepare_commit_msg_hook -- "$@"
fi
